$message = <<EOT
--------------------------------------------------------------------------

Created virtual environment for IBM Spectrum Scale.

User Guide:
https://github.com/IBM/SpectrumScaleVagrant/blob/master/README.md

To logon on the management node execute:
vagrant ssh

To connect to the Spectrum Scale GUI, in a web browser:
https://<AWS Public IP>

--------------------------------------------------------------------------
EOT


# Customize configuration specific settings
Vagrant.configure("2") do |config|

  # Dummy box for AWS provided by vagrant-aws plugin
  # See section Quickstart: https://github.com/mitchellh/vagrant-aws
  config.vm.box = "dummy-aws"

  #
  # The single node cluster comprises one node only
  #
  
  config.vm.provider :aws do |aws, override|

    # Pin the AWS region
    aws.region = "us-east-1"

    # Set AWS credentials
    aws.access_key_id     = ENV['SPECTRUM_SCALE_VAGRANT_AWS_ACCESS_KEY_ID']
    aws.secret_access_key = ENV['SPECTRUM_SCALE_VAGRANT_AWS_SECRET_ACCESS_KEY']

    # Pin the CentOS 7 AMI
    aws.ami = "ami-02eac2c0129f6376b"

    # Set user name for CentOS images
    override.ssh.username = "centos"

    # Set SSH keys
    aws.keypair_name              = ENV['SPECTRUM_SCALE_VAGRANT_AWS_KEYPAIR_NAME']
    override.ssh.private_key_path = ENV['SPECTRUM_SCALE_VAGRANT_AWS_SSH_PRIVATE_KEY_PATH']

  end    



  # Set message to be printed after VMs are up and running
  config.vm.post_up_message = $message

  # Sync Spectrum Scale install package to admin node
  #config.vm.synced_folder "../software", "/software", type: "rsync"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # Install RPMs required by Spectrum Scale Installation Toolkit
  config.vm.provision "shell",
    name:   "Install RPMs required by Spectrum Scale Installation Toolkit",
    inline: "
      /usr/bin/yum install -y\
        net-tools
    "

  # Install RPMs required by Spectrum Scale core
    config.vm.provision "shell",
    name:   "Install RPMs required by Spectrum Scale core",
    inline: "
      /usr/bin/yum install -y\
        ksh\
        m4\
        libaio
    "

  # Remove installed kernel-devel and kernel-headers to prevent version missmatches
  config.vm.provision "shell",
    name:   "Remove installed kernel-devel and kernel-headers to prevent version missmatches",
    inline: "
      /usr/bin/yum remove -y\
        kernel-devel\
        kernel-headers\
    "

  # Install RPMs required by Spectrum Scale to build portability layer
  config.vm.provision "shell",
    name:   "Install RPMs required by Spectrum Scale to build portability layer",
    inline: "
      /usr/bin/yum install -y\
        kernel-devel-$(uname -r)\
        kernel-headers-$(uname -r)\
        cpp\
        gcc\
        gcc-c++
    "

  # Install RPMs required by Spectrum Scale GUI
  config.vm.provision "shell",
    name:   "Install RPMs required by Spectrum Scale GUI",
    inline: "
      /usr/bin/yum install -y\
        libpcap\
        lsof\
        nmap-ncat\
        postgresql\
        postgresql-libs\
        postgresql-server
    "

  # Install additional RPMs required by Spectrum Scale
  config.vm.provision "shell",
    name:   "Install additional RPMs required by Spectrum Scale",
    inline: "
      /usr/bin/yum install -y\
        boost-regex\
        cyrus-sasl\
        cyrus-sasl-devel\
        keyutils-libs-devel\
        krb5-devel\
        libcom_err-devel\
        libkadm5\
        libselinux-devel\
        libsepol-devel\
        libverto-devel\
        openssl-devel\
        pcre-devel\
        perl-Class-Load\
        perl-Class-Singleton\
        perl-Data-Dumper\
        perl-Data-OptList\
        perl-DateTime\
        perl-DateTime-Locale\
        perl-DateTime-TimeZone\
        perl-List-MoreUtils\
        perl-Module-Implementation\
        perl-Module-Runtime\
        perl-Package-DeprecationManager\
        perl-Package-Stash\
        perl-Package-Stash-XS\
        perl-Params-Util\
        perl-Params-Validate\
        perl-Sub-Install\
        perl-Try-Tiny\
        zlib-devel
    "

    # Sync Spectrum Scale install package to admin node
    config.vm.synced_folder "../software", "/software", type: "rsync"

end
