$message = <<EOT
--------------------------------------------------------------------------

Created virtual environment for IBM Spectrum Scale.

User Guide:
https://github.com/IBM/SpectrumScaleVagrant/blob/master/README.md

To logon on the management node execute:
vagrant ssh

To connect to the Spectrum Scale GUI, in a web browser:
https://<AWS Public IP>

--------------------------------------------------------------------------
EOT


# Customize configuration specific settings
Vagrant.configure("2") do |config|

  # Dummy box for AWS provided by vagrant-aws plugin
  # See section Quickstart: https://github.com/mitchellh/vagrant-aws
  config.vm.box = "aws-dummy"

  #
  # The single node cluster comprises one node only
  #
  
  config.vm.provider :aws do |aws, override|

    # Pin the AWS region
    aws.region = "us-east-1"

    # Set AWS credentials
    aws.access_key_id     = ENV['SPECTRUM_SCALE_VAGRANT_AWS_ACCESS_KEY_ID']
    aws.secret_access_key = ENV['SPECTRUM_SCALE_VAGRANT_AWS_SECRET_ACCESS_KEY']

    # Pin the Spectrum Scale AMI
    aws.ami = "ami-07707895bd217b8a7"

    # Set user name for CentOS images
    override.ssh.username = "centos"

    # Set SSH keys
    aws.keypair_name              = ENV['SPECTRUM_SCALE_VAGRANT_AWS_KEYPAIR_NAME']
    override.ssh.private_key_path = ENV['SPECTRUM_SCALE_VAGRANT_AWS_SSH_PRIVATE_KEY_PATH']

  end    


  # Set message to be printed after VMs are up and running
  config.vm.post_up_message = $message

  # Sync Spectrum Scale install package to admin node
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "../../setup", "/vagrant", type: "rsync"

  # Configure permissions for shell scripts
  config.vm.provision "shell",
    name:   "Configure permissions for shell scripts",
    inline: "
      chmod 755 /vagrant/*/*.sh
    "

  # Configure /etc/hosts
  config.vm.provision "shell",
    name:   "Configure /etc/hosts",
    inline: "
      echo \"`hostname -I` m1.example.com m1\" >> /etc/hosts
    "

  # Add Spectrum Scale executables to $PATH
  config.vm.provision "shell",
    name:   "Add /usr/lpp/mmfs/bin to $PATH",
    inline: "
      cp /vagrant/files/linux/etc__profile.d__spectrumscale.sh /etc/profile.d/spectrumscale.sh
   "

  # Generate ssh keys for user root
  # Note: The Spectrum Scale installation toolkit requires root ssh
  config.vm.provision "shell",
    name:   "Generate ssh keys for user root",
    inline: "
      ssh-keygen -q -N '' -f /root/.ssh/id_rsa
      cat /root/.ssh/id_rsa.pub >> /root/.ssh/authorized_keys
    "

  # Get fingerprints of host keys
  config.vm.provision "shell",
    name:   "Get fingerprints of host keys",
    inline: "
      ssh-keyscan -t ecdsa m1             >> /root/.ssh/known_hosts 2>/dev/null
      ssh-keyscan -t ecdsa m1.example.com >> /root/.ssh/known_hosts 2>/dev/null
   "

end