# -*- mode: ruby -*-
# vi: set ft=ruby :

#
# Create virtual machine with all RPMs required by Spectrum Scale
#

$message = <<EOT
--------------------------------------------------------------------------

Created virtual machine with all RPMs required by IBM Spectrum Scale. Next
steps are to create a Vagrant box file and to destroy the virtual machine.

To create a Vagrant box file from virtual machine execute:
vagrant package SpectrumScale_base --output SpectrumScale_base.box

To destroy the virtual machine execute:
vagrant destroy

--------------------------------------------------------------------------
EOT


# Load RPMs that need to be installed on top of the CentOS base image
load File.expand_path('../../../shared/Vagrantfile.rpms', __FILE__)


Vagrant.configure("2") do |config|


  # Official CentOS 7 box
  config.vm.box = "centos/7"

  # Pin the version of the CentOS box, until project runs stable for a while
  config.vm.box_version = "2004.01"

  # Set name of virtual machine
  config.vm.define "SpectrumScale_base"

  # Set message to be printed after VMs are up and running
  config.vm.post_up_message = $message

  # No folders to sync - folders will be synced later
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # Keep insecure default ssh keys - keys will be updated later
  config.ssh.insert_key = false


end
