# -*- mode: ruby -*-
# vi: set ft=ruby :

#
# Create virtual machine with all RPMs required by Spectrum Scale
#

$message = <<EOT
--------------------------------------------------------------------------

Created virtual machine with all RPMs required by IBM Spectrum Scale. Next
steps are to create a Vagrant box file and to destroy the virtual machine.

To create a Vagrant box file from virtual machine execute:
vagrant package SpectrumScale_base --output SpectrumScale_base.box

To destroy the virtual machine execute:
vagrant destroy

--------------------------------------------------------------------------
EOT

Vagrant.configure("2") do |config|


  # Official CentOS 7 box
  config.vm.box = "centos/7"

  # Pin the version of the CentOS box, until project runs stable for a while
  config.vm.box_version = "1811.02"

  # Set name of virtual machine
  config.vm.define "SpectrumScale_base"

  # Set message to be printed after VMs are up and running
  config.vm.post_up_message = $message

  # No folders to sync - folders will be synced later
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # Keep insecure default ssh keys - keys will be updated later
  config.ssh.insert_key = false

  # Install RPMs required by Spectrum Scale Installation Toolkit
  config.vm.provision "shell",
    name:   "Install RPMs required by Spectrum Scale Installation Toolkit",
    inline: "
      /usr/bin/yum install -y\
        net-tools
    "

  # Install RPMs required by Spectrum Scale core
    config.vm.provision "shell",
    name:   "Install RPMs required by Spectrum Scale core",
    inline: "
      /usr/bin/yum install -y\
        ksh\
        m4\
        libaio
    "

  # Install RPMs required by Spectrum Scale to build portability layer
  config.vm.provision "shell",
    name:   "Install RPMs required by Spectrum Scale to build portability layer",
    inline: "
      /usr/bin/yum install -y\
        kernel-devel-3.10.0-957.1.3.el7\
        kernel-headers-3.10.0-957.1.3.el7\
        cpp\
        gcc\
        gcc-c++
    "

  # Install RPMs required by Spectrum Scale GUI
  config.vm.provision "shell",
    name:   "Install RPMs required by Spectrum Scale GUI",
    inline: "
      /usr/bin/yum install -y\
        libpcap\
        lsof\
        nmap-ncat\
        postgresql\
        postgresql-libs\
        postgresql-server
    "

  # Install additional RPMs required by Spectrum Scale
    config.vm.provision "shell",
    name:   "Install additional RPMs required by Spectrum Scale",
    inline: "
      /usr/bin/yum install -y\
        boost-regex\
        cyrus-sasl\
        cyrus-sasl-devel\
        keyutils-libs-devel\
        krb5-devel\
        libcom_err-devel\
        libkadm5\
        libselinux-devel\
        libsepol-devel\
        libverto-devel\
        openssl-devel\
        pcre-devel\
        perl-Class-Load\
        perl-Class-Singleton\
        perl-Data-Dumper\
        perl-Data-OptList\
        perl-DateTime\
        perl-DateTime-Locale\
        perl-DateTime-TimeZone\
        perl-List-MoreUtils\
        perl-Module-Implementation\
        perl-Module-Runtime\
        perl-Package-DeprecationManager\
        perl-Package-Stash\
        perl-Package-Stash-XS\
        perl-Params-Util\
        perl-Params-Validate\
        perl-Sub-Install\
        perl-Try-Tiny\
        zlib-devel
    "

end
